### ISSUE TITLE
Database error: Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by dlmw** [TeamSpeak-Systems/teamspeak-linux-docker-images#107]
```yml
services:
  teamspeak:
    image: teamspeak:3.13.7
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: teamspeak-db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD_FILE: /run/secrets/ts3_db_password
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - "teamspeak-data:/var/ts3server"
    secrets:
      - ts3_db_password
    networks:
      - teamspeak-network
      - monitoring-network
    depends_on:
      - teamspeak-db

  teamspeak-db:
    image: mariadb:11.5.2
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/ts3_db_password
      MYSQL_DATABASE: teamspeak
    volumes: 
      - "teamspeak-db:/var/lib/mysql"
    secrets:
      - ts3_db_password
    networks:
      - teamspeak-network
```

Sometimes when I try to connect to my server, I get "database error". When I check the logs of the TeamSpeak container, here's what gets logged: `2024-11-16 10:04:21.042771|ERROR   |DatabaseQuery |   |db_open() select * from clients where client_unique_id = '[REDACTED ID] error: Lost connection to MySQL server during query`. **When I try to connect 3 or 4 times in a row I can successfully connect**. What is this error from and how can I solve it?
