### ISSUE TITLE
Add support for custom entrypoint scripts

### ISSUE THREAD

**Issue by scrummer** [TeamSpeak-Systems/teamspeak-linux-docker-images#22]
### Goal
It would be cool to mount custom entrypoint scripts into the container which are executed when the container is started.

###### ./custom-entrypoint.sh
```sh
echo 'Do some stuff here (inside container) before teamspeak is getting started'
```

###### ./docker-compose.yml
```yml
version: '3'

services:
    teamspeak:
        image: teamspeak:latest
        # ...
        volumes:
            - ./custom-entrypoint.sh:/docker-entrypoint.d/custom-entrypoint.sh
        # ...
```

The current entrypoint-script then just runs every Shell-Script file inside `/docker-entrypoint.d/`.

### Why?
We have the case that we need to modify stuff inside the container **before** TeamSpeak is started. This solution would be the easiest to prevent conflicts on updates.

> Note: I can provide a PR as soon as I got the time for it. But shouldn't be a big thing.
