### ISSUE TITLE
file transfer on non-default port

### ISSUE THREAD

**Issue by daffyyyy** [TeamSpeak-Systems/teamspeak-linux-docker-images#25]
Hello, 
i am trying to start the server on a non-standard port, but file transfer does not work.
`<23:47:18> Raporty transferu „icon_3161467726”: (could not open file transfer connection)`
command that the server starts
` docker run -d -p 9988:9987/udp -p 10012:10011 -p 30034:30033 -e TS3SERVER_LICENSE=accept teamspeak`
Can I somehow remedy that the transfer would work on a different port than the default one?

**Comment by Andrioshe** [comment]
Same problem here..

**Comment by daffyyyy** [comment]
Solved, some time ago.
Change port in ts3server.ini

**Comment by chrispmangus** [comment]
Add a `-e TS3SERVER_FILETRANSFER_PORT={non-standard port}`

**Comment by Kaos1337** [comment]
> Add a `-e TS3SERVER_FILETRANSFER_PORT={non-standard port}`

The env variable TS3SERVER_FILETRANSFER_PORT isn't working, whereas the TS3SERVER_QUERY_PORT it's ok.

**Comment by peeeh** [comment]
docker run -d --net=host --name=`NameOfContainer` \
-e TS3SERVER_LICENSE=accept \
-e TS3SERVER_DEFAULT_VOICE_PORT=`CustomPort` \
-e TS3SERVER_FILETRANSFER_PORT=`CustomPort` \
-e TS3SERVER_QUERY_PORT=`CustomPort` \
-v /location/to/`NameOfContainer`/:/var/ts3server/  teamspeak

`CustomPort` for `TS3SERVER_DEFAULT_VOICE_PORT` and `TS3SERVER_QUERY_PORT` is working fine, but not for `TS3SERVER_FILETRANSFER_PORT`.

If i mount `/var/run/ts3server` the `ts3-server.ini` will be created properly but on server startup port 30033 will be used for file transfer.

**Comment by Pepreal** [comment]
Have the same issue. the port in the ini files is changed but the log file still says 30033

**Comment by chrispmangus** [comment]
> 
> 
> Add a `-e TS3SERVER_FILETRANSFER_PORT={non-standard port}`

Welp, this wasn't working actually. Need to also add `-e TS3SERVER_FILETRANSFER_IP=0.0.0.0`.

Now, it really works.

**Comment by tue-Jonas** [comment]
Of course, if you set `TS3SERVER_FILETRANSFER_PORT=30034`, you must also adjust the port forwarding accordingly by using `-p 30034:30034`. Otherwise, the clients will attempt to use port 30034, but Docker will continue to forward to port 30033, which is incorrect if `TS3SERVER_FILETRANSFER_PORT=30034` is configured.

Here is my docker-compose.yml, this works for me:
```
version: '3'

services:
  teamspeak:
    image: teamspeak:latest
    restart: always
    ports:
      - "9988:9987/udp"
      - "10012:10011"
      - "30034:30034"
    volumes:
      - ./teamspeak:/var/ts3server/
    environment:
      TS3SERVER_LICENSE: accept
      TS3SERVER_FILETRANSFER_IP: 0.0.0.0
      TS3SERVER_FILETRANSFER_PORT: 30034

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: *****
      MYSQL_DATABASE: *****

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot_data:/app/data
    restart: always
    depends_on:
      - teamspeak
      - mysql
```
