### ISSUE TITLE
Reset Serveradmin Password

### ISSUE THREAD

**Issue by SvenC56** [TeamSpeak-Systems/teamspeak-linux-docker-images#26]
Hi,

I'd like to reset the server admin password of my teamspeak server/ container. Is there a way of doing this? If not I think this would be a great implementation.

Thank you.

**Comment by SvenC56** [comment]
This solutions was helpfull for me: [TeamSpeak Forum](https://forum.teamspeak.com/threads/48255-Don-t-have-your-Server-Admin-Query-password-Look-here!?p=467868#post467868)

**Comment by muenchow** [comment]
There is also a more simple way of doing the same thing. 
Change the command to `ts3server serveradmin_password=<mypass>`

**Comment by muenchow** [comment]
```
version: '3.1'
services:
  teamspeak:
    image: teamspeak
    command: ts3server serveradmin_password=pass123
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
```
