### ISSUE TITLE
IP Addresses for ts3server.ini are set to 0.0.0.0 by default -> No IPv6

### ISSUE THREAD

**Issue by Xyaren** [TeamSpeak-Systems/teamspeak-linux-docker-images#36]
This prevents ipv6 working wihtout configuration.
Instead should just be blank.

I tricked the entryscript by using:

```
   environment:
      TS3SERVER_LICENSE: accept
      TS3SERVER_VOICE_IP: "\n"
      TS3SERVER_QUERY_SSH_IP: "\n"
      TS3SERVER_FILETRANSFER_IP: "\n"
      TS3SERVER_QUERY_IP: "\n"
```
in my docker-compose.
This basically leaves the config entry empty and will result in a binding for 0.0.0.0 and [::]
