### ISSUE TITLE
entrypoint.sh: line 50: can't create /var/run/ts3server/ts3server.ini: Permission denied :(

### ISSUE THREAD

**Issue by It0w** [TeamSpeak-Systems/teamspeak-linux-docker-images#45]
Here we go again.

Issue: https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images/issues/39#issue-521733909

Update from 3.10.2 to 3.11

**Comment by n3mur1t0r** [comment]
This is happening to me as well.

**Comment by Hedius** [comment]
Same for me. My ts3 servers are no longer starting.

**Comment by gushmazuko** [comment]
You don't need to port `/opt/ts3server/`, here's nothing important. All data is stored in `/var/lib/mysql/` and `/var/ts3server/`.

So you can do the following to save your configuration on host:
```
version: '3.1'
services:
  teamspeak:
    container_name: teamspeak
    image: teamspeak:latest
    volumes:
      - "./ts3server:/var/ts3server/"
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: you_db_password
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept

  db:
    container_name: teamspeak_db
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: you_db_password
      MYSQL_DATABASE: teamspeak
```
